-- oracle_schema.sql
--
-- Esquema Oracle para el resultado de openshift_github_audit.py.
-- Reemplaza la subida del JSON como artefacto de GitHub Actions: el script
-- inserta directamente en estas tablas al final de cada corrida.
--
-- Usa secuencia + trigger (en vez de columnas IDENTITY) para las claves
-- primarias autogeneradas, por compatibilidad con Oracle 11g en adelante.
-- Si tu Oracle es 12c+ puedes simplificar a "GENERATED BY DEFAULT AS
-- IDENTITY" y quitar las secuencias/triggers.
--
-- Ejecutar una sola vez, como el usuario/esquema que usará DB_ORACLE_USER.

-- ---------------------------------------------------------------------
-- audit_runs: una fila por cada ejecución del script
-- ---------------------------------------------------------------------
CREATE TABLE audit_runs (
    run_id                              NUMBER(19) NOT NULL,
    generated_at                        TIMESTAMP WITH TIME ZONE NOT NULL,
    namespaces_scanned                  NUMBER(10),
    deployment_containers_scanned       NUMBER(10),
    unique_repositories_found           NUMBER(10),
    deployment_containers_without_repo  NUMBER(10),
    inserted_at                         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_audit_runs PRIMARY KEY (run_id)
);

CREATE SEQUENCE seq_audit_runs START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_audit_runs_bi
BEFORE INSERT ON audit_runs
FOR EACH ROW
WHEN (NEW.run_id IS NULL)
BEGIN
    SELECT seq_audit_runs.NEXTVAL INTO :NEW.run_id FROM dual;
END;
/

-- ---------------------------------------------------------------------
-- audit_deployments: una fila por cada contenedor de cada Deployment
-- auditado, con la info del repo de GitHub correspondiente EMBEBIDA en la
-- misma fila (denormalizado a propósito): a partir del deployment y el
-- imagestream se puede leer directamente su repo, sin necesidad de cruzar
-- con otra tabla. Si varios deployments comparten repo, sus datos de repo
-- se repiten en cada fila (trade-off aceptado a cambio de que cada fila
-- quede autocontenida y fácil de consultar).
-- ---------------------------------------------------------------------
CREATE TABLE audit_deployments (
    id                          NUMBER(19) NOT NULL,
    run_id                      NUMBER(19) NOT NULL,
    namespace                   VARCHAR2(255) NOT NULL,
    deployment                  VARCHAR2(255) NOT NULL,
    container                   VARCHAR2(255) NOT NULL,
    image                       VARCHAR2(2000),
    imagestream_name            VARCHAR2(255),
    imagestream_tag             VARCHAR2(255),
    imagestream_match_method    VARCHAR2(50),
    github_detection_method     VARCHAR2(100),
    github_raw_uri              VARCHAR2(2000),
    repo_key                    VARCHAR2(500),
    repo_owner                  VARCHAR2(255),
    repo_name                   VARCHAR2(255),
    repo_url                    VARCHAR2(1000),
    repo_exists                 NUMBER(1),
    repo_private                NUMBER(1),
    repo_default_branch         VARCHAR2(255),
    repo_archived               NUMBER(1),
    repo_has_main_branch        NUMBER(1),
    repo_has_github_folder      NUMBER(1),
    repo_codeowners_found       NUMBER(1),
    repo_codeowners_path        VARCHAR2(255),
    repo_rulesets_accessible    NUMBER(1),
    repo_rulesets_count         NUMBER(10),
    repo_rulesets_names         VARCHAR2(4000),
    repo_error                  VARCHAR2(4000),
    CONSTRAINT pk_audit_deployments PRIMARY KEY (id),
    CONSTRAINT fk_audit_deployments_run FOREIGN KEY (run_id)
        REFERENCES audit_runs (run_id)
);

CREATE SEQUENCE seq_audit_deployments START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_audit_deployments_bi
BEFORE INSERT ON audit_deployments
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    SELECT seq_audit_deployments.NEXTVAL INTO :NEW.id FROM dual;
END;
/

-- ---------------------------------------------------------------------
-- audit_errors: advertencias/errores no fatales registrados en la corrida
-- ---------------------------------------------------------------------
CREATE TABLE audit_errors (
    id          NUMBER(19) NOT NULL,
    run_id      NUMBER(19) NOT NULL,
    error_text  VARCHAR2(4000),
    CONSTRAINT pk_audit_errors PRIMARY KEY (id),
    CONSTRAINT fk_audit_errors_run FOREIGN KEY (run_id)
        REFERENCES audit_runs (run_id)
);

CREATE SEQUENCE seq_audit_errors START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_audit_errors_bi
BEFORE INSERT ON audit_errors
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    SELECT seq_audit_errors.NEXTVAL INTO :NEW.id FROM dual;
END;
/

-- ---------------------------------------------------------------------
-- Índices para las consultas típicas (por corrida, por repo, por ns/deploy)
-- ---------------------------------------------------------------------
CREATE INDEX idx_audit_deps_run      ON audit_deployments (run_id);
CREATE INDEX idx_audit_deps_ns_dep   ON audit_deployments (namespace, deployment);
CREATE INDEX idx_audit_deps_repo_key ON audit_deployments (repo_key);
CREATE INDEX idx_audit_errors_run    ON audit_errors (run_id);
